export const PEOPLE = [
  { id: 0, firstName: 'Audrey', lastName: 'Harrison', team: 'red', img: 'https://randomuser.me/api/portraits/thumb/women/21.jpg' },
  { id: 1, firstName: 'Brett', lastName: 'Williams', team: 'yellow', img: 'https://randomuser.me/api/portraits/thumb/men/21.jpg' },
  { id: 2, firstName: 'Carolyn', lastName: 'Beck', team: 'green', img: 'https://randomuser.me/api/portraits/thumb/women/28.jpg' },
  { id: 3, firstName: 'Darien', lastName: 'Smith', team: 'blue', img: 'https://randomuser.me/api/portraits/thumb/men/28.jpg' },
  { id: 4, firstName: 'Emily', lastName: 'Cho', team: 'red', img: 'https://randomuser.me/api/portraits/thumb/women/24.jpg' },
  { id: 5, firstName: 'Fae', lastName: 'Kinsley', team: 'yellow', img: 'https://randomuser.me/api/portraits/thumb/women/26.jpg' },
  { id: 6, firstName: 'Greg', lastName: 'Harrison', team: 'green', img: 'https://randomuser.me/api/portraits/thumb/men/29.jpg' },
  { id: 7, firstName: 'Hannah', lastName: 'Ng', team: 'blue', img: 'https://randomuser.me/api/portraits/thumb/women/29.jpg' },
  { id: 8, firstName: 'Isabel', lastName: 'Langley', team: 'red', img: 'https://randomuser.me/api/portraits/thumb/women/31.jpg' },
  { id: 9, firstName: 'Jesus', lastName: 'Garcia', team: 'yellow', img: 'https://randomuser.me/api/portraits/thumb/men/31.jpg' },
  { id: 10, firstName: 'Katlyn', lastName: 'Francis', team: 'green', img: 'https://randomuser.me/api/portraits/thumb/women/37.jpg' },
  { id: 11, firstName: 'Laura', lastName: 'Brenner', team: 'blue', img: 'https://randomuser.me/api/portraits/thumb/women/35.jpg' },
  { id: 12, firstName: 'Martin', lastName: 'Smith', team: 'red', img: 'https://randomuser.me/api/portraits/thumb/men/35.jpg' },
  { id: 13, firstName: 'Nicole', lastName: 'Ho', team: 'yellow', img: 'https://randomuser.me/api/portraits/thumb/women/39.jpg' },
  { id: 14, firstName: 'Odessa', lastName: 'Swanson', team: 'green', img: 'https://randomuser.me/api/portraits/thumb/women/41.jpg' },
  { id: 15, firstName: 'Pete', lastName: 'Harold', team: 'blue', img: 'https://randomuser.me/api/portraits/thumb/men/41.jpg' },
  { id: 16, firstName: 'Queenie', lastName: 'Williamson', team: 'red', img: 'https://randomuser.me/api/portraits/thumb/women/42.jpg' },
  { id: 17, firstName: 'Rae', lastName: 'Edelstein', team: 'yellow', img: 'https://randomuser.me/api/portraits/thumb/women/43.jpg' },
  { id: 18, firstName: 'Stan', lastName: 'Langley', team: 'green', img: 'https://randomuser.me/api/portraits/thumb/men/43.jpg' },
  { id: 19, firstName: 'Trina', lastName: 'Abbot', team: 'blue', img: 'https://randomuser.me/api/portraits/thumb/women/48.jpg' },
  { id: 20, firstName: 'Ursula', lastName: 'Vans', team: 'red', img: 'https://randomuser.me/api/portraits/thumb/women/49.jpg' },
  { id: 21, firstName: 'Vance', lastName: 'Keller', team: 'yellow', img: 'https://randomuser.me/api/portraits/thumb/men/49.jpg' },
  { id: 22, firstName: 'Walt', lastName: 'McLeason', team: 'green', img: 'https://randomuser.me/api/portraits/thumb/men/51.jpg' },
  { id: 23, firstName: 'Xavier', lastName: 'Earl', team: 'blue', img: 'https://randomuser.me/api/portraits/thumb/men/52.jpg' },
  { id: 24, firstName: 'Yancy', lastName: 'Li', team: 'red', img: 'https://randomuser.me/api/portraits/thumb/women/52.jpg' }
]
